global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
     - targets: ["localhost:9090"]

  - job_name: email-client
      # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    metrics_path: /management/prometheus
    static_configs:
      - targets: [ '127.0.0.0:8089' ]

#      - targets:
#           # - host.docker.internal:8089
#        - http://localhost:8089